[test]
bail = true
concurrent = true
coverage = true
coveragePathIgnorePatterns = [
  "mocks/*.js",
  "test/*.js",
]
coverageReporter = ["lcov"]
dom = true
preload = ["./test/setup.js"]
randomize = true

[test.reporter]
verbose = true
